language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

branches:
  only:
  - master


# addons:
#   chrome: stable
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules
install:
  - npm run install
script:
  - npm run lint
  - npm run test -- --no-watch --no-progress
  - npm run build --prod
  # - xvfb-run npm run e2e

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  skip_cleanup: true
  region: ''