language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

# branches:
#   only:
#   - master


# addons:
#   chrome: stable
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script: # commands to run before the build step
  - npm install -g @angular/cli
cache:
  directories:
    - node_modules

script:
  - npm run lint
  - ng test --no-watch --no-progress
  - ng build --prod
  # - xvfb-run npm run e2e

# deploy:
#   provider: s3
#   access_key_id: "YOUR AWS ACCESS KEY"
#   secret_access_key: "YOUR AWS SECRET KEY"
#   bucket: "S3 Bucket"
#   skip_cleanup: true
#   region: ''